export const unlockConstants = {
  UNLOCK_RESEND_REQUEST: 'DEVISE_UNLOCK_RESEND_REQUEST',
  UNLOCK_RESEND_SUCCESS: 'DEVISE_UNLOCK_RESEND_SUCCESS',
  UNLOCK_RESEND_FAILURE: 'DEVISE_UNLOCK_RESEND_FAILURE',

  UNCLOCK_REQUEST: 'DEVISE_UNCLOCK_REQUEST',
  UNCLOCK_SUCCESS: 'DEVISE_UNCLOCK_SUCCESS',
  UNCLOCK_FAILURE: 'DEVISE_UNCLOCK_FAILURE'
}
